### ISSUE TITLE
手工焊接太費勁

### ISSUE THREAD

**Issue by Martlet-Tech** [KitSprout/AltiumDesigner_PcbLibrary#5]
电阻电容库用了, 做样的工人表示手工焊样品好困难

**Comment by hom-wang** [comment]
為了方便布局與布線，焊盤設計主要介於高密度與中密度之間，
基本上都是以自己方便焊接為主，沒有特別去考慮其他使用者的焊接能力，
畢竟是元件庫是提供給自己設計的板子使用的。

若是需要方便焊接的話，可以尋找低密度的焊盤設計喔
