### ISSUE TITLE
導入 lib 後 3D 模型全部都無法顯示？

### ISSUE THREAD

**Issue by zhen8838** [KitSprout/AltiumDesigner_PcbLibrary#8]
导入lib后3D模型全部都无法显示，请问导入此lib的正确姿势应该是？

**Comment by zhen8838** [comment]
再请问一下，为什么以前为pcblib添加过得3d模型，过一段时间使用此封装，又会提示找不到3d模型了？ 需要把3d模型文件夹添加到环境变量吗

**Comment by hom-wang** [comment]
![add](https://user-images.githubusercontent.com/4789358/41814464-968459fa-777f-11e8-8f21-fd7e9b1d2c9a.png)

使用上在 AD 裡面加入 Library 就好了，沒有甚麼特別的步驟，
不太懂你的找不到 3D 模型的意思，3D model 是跟 footprint 做在一起的，
，畫於 Mechanical 13， 能放 footprint 基本上就會有 3d 的顯示。

**Comment by zhen8838** [comment]
昨天我导入库的时候，所有的3D模型都是变成红色方框，无法刷新出来。今天我打开AD，发现所有的模型都正常显示了。感谢您的分享。

**Comment by hom-wang** [comment]
紅色方框是表示模型還在載入中，等一段時間就好了。
