### ISSUE TITLE
nice project

### ISSUE THREAD

**Issue by hall-ch** [KitSprout/AltiumDesigner_PcbLibrary#9]
很好的项目，感谢分享。我自己也在其他git平台维护自己的AD库，但是都是自己用到的器件，没有像这里这么全。
有个小建议：原理图库的信息可以更全面一些，比如增加描述、封装、制造商、制造商编码、供应商、参数、型号等，这样生成BOM就直接可以用，不用修改。

**Comment by hom-wang** [comment]
比較常使用的元件都會慢慢加入，但通常庫更新都是在有送廠製作的時候才會更改紀錄，時間不定
